<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Application\Boutquin.Trading.Application.csproj" />
    <ProjectReference Include="..\..\src\Recipes\Boutquin.Trading.Recipes.csproj" />
  </ItemGroup>

</Project>
