// Copyright (c) 2023-2026 Pierre G. Boutquin. All rights reserved.
//
//   Licensed under the Apache License, Version 2.0 (the "License").
//   You may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

namespace Boutquin.Trading.Application.PositionSizing;

using Domain.ValueObjects;

/// <summary>
/// The FixedWeightPositionSizer class implements the IPositionSizer interface, using fixed asset weights to determine
/// the desired positions. The weights are expressed as a percentage of the total strategy value in the base currency.
/// </summary>
public sealed class FixedWeightPositionSizer : IPositionSizer
{
    private readonly IReadOnlyDictionary<Asset, decimal> _fixedAssetWeights;
    private readonly CurrencyCode _baseCurrency;
    private readonly decimal _cashBufferPercent;
    private readonly bool _renormalizeForSignaledAssets;

    /// <summary>
    /// Initializes a new instance of the FixedWeightPositionSizer class with the given fixed asset weights and base currency.
    /// </summary>
    /// <param name="fixedAssetWeights">A dictionary containing the fixed asset weights, with asset names as keys and weights as values.</param>
    /// <param name="baseCurrency">The base currency used for calculations and conversions.</param>
    /// <param name="cashBufferPercent">Fraction of portfolio value to reserve as cash buffer (0.0–0.99). Default 0 for backward compatibility.</param>
    /// <param name="renormalizeForSignaledAssets">When true, renormalize weights among signaled assets so the portfolio stays fully invested
    /// even when some assets are not yet available (e.g., dynamic universe). Default false for backward compatibility.</param>
    /// <exception cref="EmptyOrNullDictionaryException">
    /// Throws this exception if the fixed asset weights dictionary is empty or null.
    /// </exception>
    /// <exception cref="ArgumentOutOfRangeException">
    /// Throws this exception if the base currency is undefined or cashBufferPercent is out of range.
    /// </exception>
    public FixedWeightPositionSizer(
        IReadOnlyDictionary<Asset, decimal> fixedAssetWeights,
        CurrencyCode baseCurrency,
        decimal cashBufferPercent = 0m,
        bool renormalizeForSignaledAssets = false)
    {
        // Validate parameters
        Guard.AgainstEmptyOrNullReadOnlyDictionary(() => fixedAssetWeights); // Throws EmptyOrNullDictionaryException
        Guard.AgainstUndefinedEnumValue(() => baseCurrency); // Throws ArgumentOutOfRangeException

        if (cashBufferPercent < 0 || cashBufferPercent >= 1)
        {
            throw new ArgumentOutOfRangeException(nameof(cashBufferPercent), cashBufferPercent, "Cash buffer percent must be >= 0 and < 1.");
        }

        // ROB-A03: Validate weights are non-negative
        foreach (var (_, weight) in fixedAssetWeights)
        {
            if (weight < 0)
            {
                throw new ArgumentOutOfRangeException(nameof(fixedAssetWeights), "Asset weights must be non-negative.");
            }
        }

        _fixedAssetWeights = fixedAssetWeights;
        _baseCurrency = baseCurrency;
        _cashBufferPercent = cashBufferPercent;
        _renormalizeForSignaledAssets = renormalizeForSignaledAssets;
    }

    /// <summary>
    /// Computes the desired position sizes for all assets in the strategy based on the fixed asset weights and historical market data.
    /// </summary>
    /// <param name="timestamp">The timestamp of the signal event.</param>
    /// <param name="signalType">The type of signal generated by the trading strategy.</param>
    /// <param name="strategy">The strategy instance to use for computing the position sizes.</param>
    /// <param name="historicalMarketData">The historical market data to use for calculations.</param>
    /// <param name="historicalFxConversionRates">The historical foreign exchange conversion rates to use for currency conversions.</param>
    /// <returns>A dictionary containing the desired position sizes for all assets in the strategy.</returns>
    /// <exception cref="ArgumentNullException">
    /// Throws this exception if the signal type or strategy is null.
    /// </exception>
    /// <exception cref="EmptyOrNullDictionaryException">
    /// Throws this exception if the historical market data or historical FX conversion rates dictionaries are empty or null.
    /// </exception>
    public IReadOnlyDictionary<Asset, int> ComputePositionSizes(
        DateOnly timestamp,
        IReadOnlyDictionary<Asset, SignalType> signalType,
        IStrategy strategy,
        IReadOnlyDictionary<DateOnly, SortedDictionary<Asset, MarketData>> historicalMarketData,
        IReadOnlyDictionary<DateOnly, SortedDictionary<CurrencyCode, decimal>> historicalFxConversionRates)
    {
        // Validate parameters
        Guard.AgainstNull(() => signalType); // Throws ArgumentNullException
        Guard.AgainstNull(() => strategy); // Throws ArgumentNullException
        Guard.AgainstEmptyOrNullReadOnlyDictionary(() => historicalMarketData); // Throws EmptyOrNullDictionaryException
        Guard.AgainstEmptyOrNullReadOnlyDictionary(() => historicalFxConversionRates); // Throws EmptyOrNullDictionaryException

        var positionSizes = new Dictionary<Asset, int>();

        // Compute the total value of the strategy in the base currency
        var totalStrategyValue = strategy.ComputeTotalValue(
            timestamp,
            _baseCurrency,
            historicalMarketData,
            historicalFxConversionRates);
        var allocatableValue = totalStrategyValue * (1m - _cashBufferPercent);

        // Compute renormalization factor for signaled assets (dynamic universe support).
        // When renormalization is enabled, weights are scaled so the portfolio stays fully
        // invested even when some assets aren't yet available.
        var renormFactor = 1m;
        if (_renormalizeForSignaledAssets)
        {
            var signaledWeightSum = strategy.Assets.Keys
                .Where(a => signalType.ContainsKey(a) && _fixedAssetWeights.ContainsKey(a))
                .Sum(a => _fixedAssetWeights[a]);
            renormFactor = signaledWeightSum > 0 ? 1m / signaledWeightSum : 0m;
        }

        // Calculate the desired position size for each asset based on the fixed asset weights
        foreach (var asset in strategy.Assets.Keys)
        {
            // Skip assets without signals (e.g., not yet available in dynamic universe)
            if (!signalType.ContainsKey(asset))
            {
                continue;
            }

            // ROB-A02: Single lookup with TryGetValue
            if (!_fixedAssetWeights.TryGetValue(asset, out var assetWeight))
            {
                throw new InvalidOperationException($"Fixed asset weight not found for asset \'{asset}\'.");
            }

            var desiredAssetValue = allocatableValue * assetWeight * renormFactor;

            // BUG-A08: Null-check inner dictionary before access
            if (!historicalMarketData.TryGetValue(timestamp, out var marketDataForDate) ||
                marketDataForDate == null ||
                !marketDataForDate.TryGetValue(asset, out var marketData))
            {
                throw new InvalidOperationException($"Market data not found for asset \'{asset}\' on {timestamp}.");
            }

            // BUG-A09: Guard against division by zero on AdjustedClose
            if (marketData.AdjustedClose == 0)
            {
                throw new InvalidOperationException($"AdjustedClose is zero for asset \'{asset}\' on {timestamp}.");
            }

            // M10: Round instead of truncate to avoid systematic downward bias
            var positionSize = (int)Math.Round(desiredAssetValue / marketData.AdjustedClose, MidpointRounding.AwayFromZero);
            positionSizes[asset] = positionSize;
        }

        return positionSizes;
    }
}
