#!/usr/bin/env python3
"""
Generate cross-language verification vectors for analytics components.

Phase 4D-4H of the verification roadmap.
Components: BrinsonFachler, FactorRegressor, CorrelationAnalyzer,
            EffectiveNumberOfBets, DrawdownAnalyzer.

All Python reference implementations replicate the EXACT C# algorithms.

CORRECTNESS VALIDATION (three layers):
  1. Library cross-references — OLS vs statsmodels, correlation vs numpy.corrcoef.
  2. Analytical solutions — ENB(identity)=N, BF effects sum to active return,
     OLS on perfect linear data.
  3. Property-based checks — R² ∈ [0,1], |correlation| ≤ 1, drawdown depths ∈ [-1,0].

NOTE: Existing vectors (attribution.json, regression.json, correlation.json)
were generated by generate_vectors.py. This generator creates ADDITIONAL vectors
with edge cases and gradient/structure verification. C# tests should consume
BOTH the existing and new vectors.
"""

import json
import math
from datetime import date, timedelta
from pathlib import Path

import numpy as np

VECTORS_DIR = Path(__file__).parent / "vectors"
VECTORS_DIR.mkdir(exist_ok=True)

RNG = np.random.default_rng(seed=405)  # Distinct seed for Phase 4 analytics

# ═══════════════════════════════════════════════════════════════════════════
# Correctness tracking
# ═══════════════════════════════════════════════════════════════════════════

HARD_CHECKS: list[tuple[str, bool]] = []
QUALITY_CHECKS: list[tuple[str, bool, str]] = []


def hard_check(name: str, condition: bool):
    HARD_CHECKS.append((name, condition))
    assert condition, f"HARD CHECK FAILED: {name}"


def quality_check(name: str, actual: float, expected: float, rel_tol: float = 0.01):
    if expected == 0:
        gap = abs(actual)
        passed = gap < 1e-6
    else:
        gap = abs(actual - expected) / abs(expected)
        passed = gap < rel_tol
    QUALITY_CHECKS.append((name, passed, f"gap={gap:.6f}"))
    if not passed:
        print(f"  ⚠ QUALITY GAP: {name} — actual={actual:.8f}, expected={expected:.8f}, gap={gap:.4%}")


def save(name: str, data: dict) -> None:
    def convert(obj):
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        if isinstance(obj, (np.float64, np.float32)):
            return float(obj)
        if isinstance(obj, (np.int64, np.int32)):
            return int(obj)
        if isinstance(obj, date):
            return obj.isoformat()
        raise TypeError(f"Cannot serialize {type(obj)}")

    with open(VECTORS_DIR / f"{name}.json", "w") as f:
        json.dump(data, f, indent=2, default=convert)
    print(f"  -> {name}.json")


# ═══════════════════════════════════════════════════════════════════════════
# Brinson-Fachler Attribution (matches C# BrinsonFachlerAttributor)
# ═══════════════════════════════════════════════════════════════════════════

def brinson_fachler(assets, port_weights, bench_weights, port_returns, bench_returns):
    """Single-period Brinson-Fachler attribution. Matches C#."""
    bench_total = sum(bench_weights[a] * bench_returns[a] for a in assets)

    alloc_effects = {}
    sel_effects = {}
    inter_effects = {}

    for a in assets:
        wp = port_weights[a]
        wb = bench_weights[a]
        rp = port_returns[a]
        rb = bench_returns[a]
        alloc_effects[a] = (wp - wb) * (rb - bench_total)
        sel_effects[a] = wb * (rp - rb)
        inter_effects[a] = (wp - wb) * (rp - rb)

    total_alloc = sum(alloc_effects.values())
    total_sel = sum(sel_effects.values())
    total_inter = sum(inter_effects.values())
    total_active = total_alloc + total_sel + total_inter

    return {
        "allocation_effect": total_alloc,
        "selection_effect": total_sel,
        "interaction_effect": total_inter,
        "total_active_return": total_active,
        "asset_allocation_effects": alloc_effects,
        "asset_selection_effects": sel_effects,
        "asset_interaction_effects": inter_effects,
    }


# ═══════════════════════════════════════════════════════════════════════════
# Factor Regression (matches C# FactorRegressor — Gaussian elimination)
# ═══════════════════════════════════════════════════════════════════════════

def factor_regression(portfolio_returns, factor_names, factor_returns):
    """OLS regression via normal equations with Gaussian elimination + partial pivoting.
    Matches C# FactorRegressor exactly."""
    t_obs = len(portfolio_returns)
    k = len(factor_names)

    # Build X matrix: T × (K+1) — intercept + factors
    x = np.ones((t_obs, k + 1))
    for j, name in enumerate(factor_names):
        x[:, j + 1] = factor_returns[name]

    y = np.array(portfolio_returns)

    # X'X and X'y
    xtx = x.T @ x
    xty = x.T @ y

    # Gaussian elimination with partial pivoting
    n_cols = k + 1
    aug = np.zeros((n_cols, n_cols + 1))
    aug[:, :n_cols] = xtx
    aug[:, n_cols] = xty

    for col in range(n_cols):
        # Partial pivoting: find max in column
        max_row = col
        max_val = abs(aug[col, col])
        for row in range(col + 1, n_cols):
            if abs(aug[row, col]) > max_val:
                max_val = abs(aug[row, col])
                max_row = row
        if max_row != col:
            aug[[col, max_row]] = aug[[max_row, col]]

        pivot = aug[col, col]
        if abs(pivot) < 1e-14:
            raise ValueError("Singular matrix in factor regression")

        # Eliminate below
        for row in range(col + 1, n_cols):
            factor = aug[row, col] / pivot
            aug[row, col:] -= factor * aug[col, col:]

    # Back substitution
    beta = np.zeros(n_cols)
    for i in range(n_cols - 1, -1, -1):
        beta[i] = (aug[i, n_cols] - sum(aug[i, j] * beta[j]
                                          for j in range(i + 1, n_cols))) / aug[i, i]

    alpha = beta[0]
    factor_loadings = {name: beta[j + 1] for j, name in enumerate(factor_names)}

    # R² and residual std error
    y_pred = x @ beta
    residuals = y - y_pred
    ss_res = np.sum(residuals ** 2)
    y_mean = np.mean(y)
    ss_tot = np.sum((y - y_mean) ** 2)
    r_squared = max(0.0, min(1.0, 1.0 - ss_res / ss_tot)) if ss_tot > 0 else 0.0

    dof = t_obs - k - 1
    residual_std_error = math.sqrt(ss_res / dof) if dof > 0 else 0.0

    return {
        "alpha": alpha,
        "factor_loadings": factor_loadings,
        "r_squared": r_squared,
        "residual_std_error": residual_std_error,
    }


# ═══════════════════════════════════════════════════════════════════════════
# Correlation Analyzer (matches C# CorrelationAnalyzer)
# ═══════════════════════════════════════════════════════════════════════════

def correlation_analysis(returns, weights):
    """Compute correlation matrix and diversification ratio. Matches C#."""
    n = returns.shape[0]
    t_obs = returns.shape[1]

    # Sample covariance (N-1 divisor)
    means = returns.mean(axis=1)
    cov = np.zeros((n, n))
    for i in range(n):
        for j in range(i, n):
            c = sum((returns[i, k] - means[i]) * (returns[j, k] - means[j])
                    for k in range(t_obs)) / (t_obs - 1)
            cov[i, j] = c
            cov[j, i] = c

    # Correlation matrix
    stds = np.sqrt(np.diag(cov))
    corr = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if stds[i] == 0 or stds[j] == 0:
                corr[i, j] = 1.0 if i == j else 0.0
            else:
                corr[i, j] = cov[i, j] / (stds[i] * stds[j])

    # Diversification ratio
    weighted_avg_vol = sum(weights[i] * stds[i] for i in range(n))
    port_var = sum(weights[i] * weights[j] * cov[i, j]
                   for i in range(n) for j in range(n))
    port_vol = math.sqrt(max(0.0, port_var))
    dr = weighted_avg_vol / port_vol if port_vol > 0 else 1.0

    return {
        "correlation_matrix": corr,
        "diversification_ratio": dr,
        "covariance_matrix": cov,
        "std_devs": stds,
    }


# ═══════════════════════════════════════════════════════════════════════════
# Effective Number of Bets (matches C# EffectiveNumberOfBets — Jacobi)
# ═══════════════════════════════════════════════════════════════════════════

def effective_number_of_bets(corr_matrix):
    """ENB via eigenvalue entropy. Uses numpy eigh (not Jacobi).
    C# uses Jacobi, so expect PrecisionStatistical for eigenvector-derived values."""
    eigenvalues = np.linalg.eigvalsh(corr_matrix)
    eigenvalues = np.maximum(eigenvalues, 0.0)  # Clamp negatives
    eigenvalues = np.sort(eigenvalues)[::-1]     # Sort descending

    total = eigenvalues.sum()
    if total <= 0:
        return 1.0, eigenvalues

    probs = eigenvalues / total
    entropy = 0.0
    for p in probs:
        if p > 0:
            entropy -= p * math.log(p)

    enb = math.exp(entropy)
    return enb, eigenvalues


# ═══════════════════════════════════════════════════════════════════════════
# Drawdown Analyzer (matches C# DrawdownAnalyzer)
# ═══════════════════════════════════════════════════════════════════════════

def analyze_drawdown_periods(dates, equity_values):
    """Identify drawdown periods. Matches C# DrawdownAnalyzer.AnalyzeDrawdownPeriods."""
    periods = []
    n = len(dates)

    peak_val = equity_values[0]
    peak_date = dates[0]
    peak_idx = 0
    trough_val = equity_values[0]
    trough_date = dates[0]
    trough_idx = 0
    in_drawdown = False

    for i in range(1, n):
        val = equity_values[i]

        if val >= peak_val:
            if in_drawdown:
                # Recovery — record the drawdown period
                depth = (trough_val - peak_val) / peak_val
                # C# uses i - peakIndex (peak to recovery), not peak to trough
                duration_days = i - peak_idx
                recovery_days = i - trough_idx
                periods.append({
                    "start_date": peak_date.isoformat(),
                    "trough_date": trough_date.isoformat(),
                    "recovery_date": dates[i].isoformat(),
                    "depth": depth,
                    "duration_days": duration_days,
                    "recovery_days": recovery_days,
                })
                in_drawdown = False

            peak_val = val
            peak_date = dates[i]
            peak_idx = i
            trough_val = val
            trough_date = dates[i]
            trough_idx = i
        else:
            in_drawdown = True
            if val < trough_val:
                trough_val = val
                trough_date = dates[i]
                trough_idx = i

    # Handle ongoing drawdown at end
    if in_drawdown:
        depth = (trough_val - peak_val) / peak_val
        # C# uses entries.Count - 1 - peakIndex (peak to end of series)
        duration_days = n - 1 - peak_idx
        periods.append({
            "start_date": peak_date.isoformat(),
            "trough_date": trough_date.isoformat(),
            "recovery_date": None,
            "depth": depth,
            "duration_days": duration_days,
            "recovery_days": None,
        })

    return periods


# ═══════════════════════════════════════════════════════════════════════════
# Generator: BrinsonFachler
# ═══════════════════════════════════════════════════════════════════════════

def gen_brinson_fachler():
    """Phase 4D: BrinsonFachler Attribution."""
    print("Phase 4D: BrinsonFachler Attribution")

    # Standard 4-sector case
    assets = ["Equities", "Bonds", "Commodities", "RealEstate"]
    pw = {"Equities": 0.50, "Bonds": 0.25, "Commodities": 0.15, "RealEstate": 0.10}
    bw = {"Equities": 0.40, "Bonds": 0.35, "Commodities": 0.15, "RealEstate": 0.10}
    pr = {"Equities": 0.10, "Bonds": 0.03, "Commodities": -0.02, "RealEstate": 0.06}
    br = {"Equities": 0.08, "Bonds": 0.04, "Commodities": -0.01, "RealEstate": 0.05}

    result_4sec = brinson_fachler(assets, pw, bw, pr, br)

    # --- Layer 2: Analytical ---
    # Effects must sum to total active return
    port_total = sum(pw[a] * pr[a] for a in assets)
    bench_total = sum(bw[a] * br[a] for a in assets)
    active_return = port_total - bench_total
    hard_check("BF: effects sum to active return",
               abs(result_4sec["total_active_return"] - active_return) < 1e-14)
    hard_check("BF: alloc+sel+inter = total",
               abs(result_4sec["allocation_effect"] + result_4sec["selection_effect"] +
                   result_4sec["interaction_effect"] - result_4sec["total_active_return"]) < 1e-14)

    # Identical weights: allocation = 0, interaction = 0
    same_w = {"Equities": 0.40, "Bonds": 0.35, "Commodities": 0.15, "RealEstate": 0.10}
    result_same_w = brinson_fachler(assets, same_w, same_w, pr, br)
    hard_check("BF: identical weights → allocation=0", abs(result_same_w["allocation_effect"]) < 1e-14)
    hard_check("BF: identical weights → interaction=0", abs(result_same_w["interaction_effect"]) < 1e-14)

    # Identical returns: selection = 0, interaction = 0
    same_r = {"Equities": 0.08, "Bonds": 0.04, "Commodities": -0.01, "RealEstate": 0.05}
    result_same_r = brinson_fachler(assets, pw, bw, same_r, same_r)
    hard_check("BF: identical returns → selection=0", abs(result_same_r["selection_effect"]) < 1e-14)
    hard_check("BF: identical returns → interaction=0", abs(result_same_r["interaction_effect"]) < 1e-14)

    # --- Layer 3: Properties ---
    # Per-asset effects sum to totals
    hard_check("BF: per-asset alloc sums",
               abs(sum(result_4sec["asset_allocation_effects"].values()) -
                   result_4sec["allocation_effect"]) < 1e-14)
    hard_check("BF: per-asset sel sums",
               abs(sum(result_4sec["asset_selection_effects"].values()) -
                   result_4sec["selection_effect"]) < 1e-14)
    hard_check("BF: per-asset inter sums",
               abs(sum(result_4sec["asset_interaction_effects"].values()) -
                   result_4sec["interaction_effect"]) < 1e-14)

    # Edge: 2-sector
    assets_2 = ["Equities", "Bonds"]
    pw_2 = {"Equities": 0.70, "Bonds": 0.30}
    bw_2 = {"Equities": 0.60, "Bonds": 0.40}
    pr_2 = {"Equities": 0.12, "Bonds": 0.02}
    br_2 = {"Equities": 0.10, "Bonds": 0.03}
    result_2sec = brinson_fachler(assets_2, pw_2, bw_2, pr_2, br_2)
    hard_check("BF 2-sector: effects sum to active",
               abs(result_2sec["total_active_return"] -
                   (sum(pw_2[a] * pr_2[a] for a in assets_2) -
                    sum(bw_2[a] * br_2[a] for a in assets_2))) < 1e-14)

    save("analytics_brinson_fachler", {
        "cases": {
            "four_sector": {
                "assets": assets,
                "portfolio_weights": pw,
                "benchmark_weights": bw,
                "portfolio_returns": pr,
                "benchmark_returns": br,
                **result_4sec,
            },
            "identical_weights": {
                "assets": assets,
                "portfolio_weights": same_w,
                "benchmark_weights": same_w,
                "portfolio_returns": pr,
                "benchmark_returns": br,
                **result_same_w,
            },
            "identical_returns": {
                "assets": assets,
                "portfolio_weights": pw,
                "benchmark_weights": bw,
                "portfolio_returns": same_r,
                "benchmark_returns": same_r,
                **result_same_r,
            },
            "two_sector": {
                "assets": assets_2,
                "portfolio_weights": pw_2,
                "benchmark_weights": bw_2,
                "portfolio_returns": pr_2,
                "benchmark_returns": br_2,
                **result_2sec,
            },
        },
        "notes": "Brinson-Fachler single-period attribution. "
                 "Alloc=(Wp-Wb)(Rb_i-Rb_total), Sel=Wb(Rp_i-Rb_i), Inter=(Wp-Wb)(Rp_i-Rb_i).",
    })


# ═══════════════════════════════════════════════════════════════════════════
# Generator: FactorRegressor
# ═══════════════════════════════════════════════════════════════════════════

def gen_factor_regression():
    """Phase 4E: Factor Regression — OLS with Gaussian elimination."""
    print("Phase 4E: Factor Regression")

    # Generate synthetic factor data
    t_obs = 120
    factor_names = ["Mkt-RF", "SMB", "HML"]
    factor_data = {
        "Mkt-RF": RNG.normal(0.005, 0.04, t_obs),
        "SMB": RNG.normal(0.002, 0.03, t_obs),
        "HML": RNG.normal(0.001, 0.025, t_obs),
    }

    # Generate portfolio returns with known loadings
    true_alpha = 0.001
    true_betas = {"Mkt-RF": 1.1, "SMB": 0.3, "HML": -0.2}
    noise = RNG.normal(0, 0.01, t_obs)
    portfolio_returns = (true_alpha +
                         true_betas["Mkt-RF"] * factor_data["Mkt-RF"] +
                         true_betas["SMB"] * factor_data["SMB"] +
                         true_betas["HML"] * factor_data["HML"] +
                         noise)

    result = factor_regression(portfolio_returns.tolist(),
                                factor_names,
                                {k: v.tolist() for k, v in factor_data.items()})

    # --- Layer 1: Library cross-check vs statsmodels ---
    try:
        import statsmodels.api as sm
        x_sm = np.column_stack([factor_data[n] for n in factor_names])
        x_sm = sm.add_constant(x_sm)
        model = sm.OLS(portfolio_returns, x_sm).fit()
        quality_check("FactorReg: alpha vs statsmodels", result["alpha"], model.params[0])
        quality_check("FactorReg: R² vs statsmodels", result["r_squared"], model.rsquared)
        for j, name in enumerate(factor_names):
            quality_check(f"FactorReg: beta_{name} vs statsmodels",
                          result["factor_loadings"][name], model.params[j + 1])
    except ImportError:
        print("  statsmodels not available — skipping Layer 1 cross-check")

    # --- Layer 2: Analytical ---
    # R² should be high since we generated data with known structure
    hard_check("FactorReg: R² > 0.8 (structured data)", result["r_squared"] > 0.8)

    # Perfect linear data: R² = 1
    perfect_returns = (0.002 +
                       1.5 * factor_data["Mkt-RF"] +
                       0.5 * factor_data["SMB"] -
                       0.3 * factor_data["HML"])
    result_perfect = factor_regression(perfect_returns.tolist(),
                                        factor_names,
                                        {k: v.tolist() for k, v in factor_data.items()})
    hard_check("FactorReg: perfect data → R²≈1", abs(result_perfect["r_squared"] - 1.0) < 1e-8)
    hard_check("FactorReg: perfect data → alpha≈0.002", abs(result_perfect["alpha"] - 0.002) < 1e-8)
    hard_check("FactorReg: perfect data → beta_Mkt≈1.5",
               abs(result_perfect["factor_loadings"]["Mkt-RF"] - 1.5) < 1e-8)

    # --- Layer 3: Properties ---
    hard_check("FactorReg: R² ∈ [0,1]", 0.0 <= result["r_squared"] <= 1.0)
    hard_check("FactorReg: residual std > 0", result["residual_std_error"] > 0)

    # Single factor
    result_1f = factor_regression(portfolio_returns.tolist(),
                                   ["Mkt-RF"],
                                   {"Mkt-RF": factor_data["Mkt-RF"].tolist()})
    hard_check("FactorReg: single factor R² ∈ [0,1]", 0.0 <= result_1f["r_squared"] <= 1.0)

    # 5-factor
    factor_data_5 = dict(factor_data)
    factor_data_5["RMW"] = RNG.normal(0.001, 0.02, t_obs)
    factor_data_5["CMA"] = RNG.normal(0.001, 0.02, t_obs)
    factor_names_5 = ["Mkt-RF", "SMB", "HML", "RMW", "CMA"]
    result_5f = factor_regression(portfolio_returns.tolist(),
                                   factor_names_5,
                                   {k: v.tolist() for k, v in factor_data_5.items()})
    hard_check("FactorReg: 5-factor R² ∈ [0,1]", 0.0 <= result_5f["r_squared"] <= 1.0)

    save("analytics_factor_regression", {
        "cases": {
            "three_factor": {
                "portfolio_returns": portfolio_returns.tolist(),
                "factor_names": factor_names,
                "factor_returns": {k: v.tolist() for k, v in factor_data.items()},
                **result,
            },
            "perfect_linear": {
                "portfolio_returns": perfect_returns.tolist(),
                "factor_names": factor_names,
                "factor_returns": {k: v.tolist() for k, v in factor_data.items()},
                **result_perfect,
            },
            "single_factor": {
                "portfolio_returns": portfolio_returns.tolist(),
                "factor_names": ["Mkt-RF"],
                "factor_returns": {"Mkt-RF": factor_data["Mkt-RF"].tolist()},
                **result_1f,
            },
            "five_factor": {
                "portfolio_returns": portfolio_returns.tolist(),
                "factor_names": factor_names_5,
                "factor_returns": {k: v.tolist() for k, v in factor_data_5.items()},
                **result_5f,
            },
        },
        "notes": "OLS factor regression via Gaussian elimination with partial pivoting. "
                 "Matches C# FactorRegressor.",
    })


# ═══════════════════════════════════════════════════════════════════════════
# Generator: CorrelationAnalyzer
# ═══════════════════════════════════════════════════════════════════════════

def gen_correlation():
    """Phase 4F: CorrelationAnalyzer — matrix + diversification ratio."""
    print("Phase 4F: CorrelationAnalyzer")

    # 3-asset, 100 observations
    n, t_obs = 3, 100
    returns = RNG.normal(0.001, 0.02, (n, t_obs))
    weights = np.array([0.5, 0.3, 0.2])

    result = correlation_analysis(returns, weights)

    # --- Layer 1: Library cross-check vs numpy ---
    np_corr = np.corrcoef(returns)
    for i in range(n):
        for j in range(n):
            quality_check(f"Corr[{i},{j}] vs numpy", result["correlation_matrix"][i, j], np_corr[i, j])

    # --- Layer 2: Analytical ---
    # Diagonal = 1
    for i in range(n):
        hard_check(f"Corr: diagonal[{i}]=1", abs(result["correlation_matrix"][i, i] - 1.0) < 1e-14)
    # Symmetric
    for i in range(n):
        for j in range(i + 1, n):
            hard_check(f"Corr: symmetric[{i},{j}]",
                       abs(result["correlation_matrix"][i, j] - result["correlation_matrix"][j, i]) < 1e-14)

    # Identity correlation → DR = sqrt(N) for equal weights
    ident_cov = np.eye(n) * 0.0004  # All same vol, zero correlation
    ident_stds = np.sqrt(np.diag(ident_cov))
    ew = np.array([1.0 / n] * n)
    wav = sum(ew[i] * ident_stds[i] for i in range(n))
    pv = ew @ ident_cov @ ew
    expected_dr = wav / math.sqrt(pv)
    hard_check("Corr: uncorrelated DR ≈ sqrt(N)",
               abs(expected_dr - math.sqrt(n)) < 1e-10)

    # --- Layer 3: Properties ---
    hard_check("Corr: DR ≥ 1", result["diversification_ratio"] >= 1.0 - 1e-10)
    for i in range(n):
        for j in range(n):
            hard_check(f"Corr: |corr[{i},{j}]| ≤ 1",
                       abs(result["correlation_matrix"][i, j]) <= 1.0 + 1e-10)

    # Edge: 2-asset
    returns_2 = RNG.normal(0.001, 0.02, (2, 100))
    w_2 = np.array([0.6, 0.4])
    result_2 = correlation_analysis(returns_2, w_2)
    hard_check("Corr 2-asset: DR ≥ 1", result_2["diversification_ratio"] >= 1.0 - 1e-10)

    # Edge: 5-asset
    returns_5 = RNG.normal(0.001, 0.02, (5, 200))
    w_5 = np.array([0.3, 0.25, 0.2, 0.15, 0.1])
    result_5 = correlation_analysis(returns_5, w_5)
    hard_check("Corr 5-asset: DR ≥ 1", result_5["diversification_ratio"] >= 1.0 - 1e-10)

    save("analytics_correlation", {
        "cases": {
            "three_asset": {
                "returns": returns.tolist(),
                "weights": weights.tolist(),
                "correlation_matrix": result["correlation_matrix"].tolist(),
                "diversification_ratio": result["diversification_ratio"],
            },
            "two_asset": {
                "returns": returns_2.tolist(),
                "weights": w_2.tolist(),
                "correlation_matrix": result_2["correlation_matrix"].tolist(),
                "diversification_ratio": result_2["diversification_ratio"],
            },
            "five_asset": {
                "returns": returns_5.tolist(),
                "weights": w_5.tolist(),
                "correlation_matrix": result_5["correlation_matrix"].tolist(),
                "diversification_ratio": result_5["diversification_ratio"],
            },
        },
        "notes": "CorrelationAnalyzer: sample covariance (N-1), correlation, diversification ratio.",
    })


# ═══════════════════════════════════════════════════════════════════════════
# Generator: EffectiveNumberOfBets
# ═══════════════════════════════════════════════════════════════════════════

def gen_enb():
    """Phase 4G: Effective Number of Bets — eigenvalue entropy."""
    print("Phase 4G: Effective Number of Bets")

    # --- Layer 2: Analytical ---
    # Identity matrix: ENB = N
    for n in [2, 3, 5]:
        enb_ident, _ = effective_number_of_bets(np.eye(n))
        hard_check(f"ENB: identity {n}×{n} = {n}", abs(enb_ident - n) < 1e-8)

    # Rank-1 matrix (all perfectly correlated): ENB = 1
    ones_3 = np.ones((3, 3))
    enb_rank1, _ = effective_number_of_bets(ones_3)
    hard_check("ENB: rank-1 (all corr=1) = 1", abs(enb_rank1 - 1.0) < 1e-8)

    # --- Layer 3: Properties ---
    # ENB ∈ [1, N]
    # Use a realistic correlation matrix
    n_test = 4
    returns_test = RNG.normal(0.001, 0.02, (n_test, 200))
    cov_test = np.cov(returns_test, ddof=1)
    stds_test = np.sqrt(np.diag(cov_test))
    corr_test = cov_test / np.outer(stds_test, stds_test)
    np.fill_diagonal(corr_test, 1.0)
    enb_test, eigenvalues_test = effective_number_of_bets(corr_test)
    hard_check(f"ENB: {n_test}-asset ∈ [1, {n_test}]", 1.0 - 1e-8 <= enb_test <= n_test + 1e-8)

    # More correlated → lower ENB
    # Create highly correlated matrix
    high_corr = np.full((3, 3), 0.9)
    np.fill_diagonal(high_corr, 1.0)
    enb_high, _ = effective_number_of_bets(high_corr)
    low_corr = np.full((3, 3), 0.1)
    np.fill_diagonal(low_corr, 1.0)
    enb_low, _ = effective_number_of_bets(low_corr)
    hard_check("ENB: high corr < low corr", enb_high < enb_low + 1e-8)

    # From returns (convenience method)
    returns_5 = RNG.normal(0.001, 0.02, (5, 252))
    cov_5 = np.cov(returns_5, ddof=1)
    stds_5 = np.sqrt(np.diag(cov_5))
    corr_5 = cov_5 / np.outer(stds_5, stds_5)
    np.fill_diagonal(corr_5, 1.0)
    enb_5, eigenvalues_5 = effective_number_of_bets(corr_5)
    hard_check("ENB: 5-asset ∈ [1, 5]", 1.0 - 1e-8 <= enb_5 <= 5.0 + 1e-8)

    save("analytics_enb", {
        "cases": {
            "identity_3": {
                "correlation_matrix": np.eye(3).tolist(),
                "enb": 3.0,
            },
            "identity_5": {
                "correlation_matrix": np.eye(5).tolist(),
                "enb": 5.0,
            },
            "rank_1": {
                "correlation_matrix": ones_3.tolist(),
                "enb": 1.0,
            },
            "high_corr": {
                "correlation_matrix": high_corr.tolist(),
                "enb": enb_high,
            },
            "low_corr": {
                "correlation_matrix": low_corr.tolist(),
                "enb": enb_low,
            },
            "realistic_4": {
                "correlation_matrix": corr_test.tolist(),
                "enb": enb_test,
                "eigenvalues": eigenvalues_test.tolist(),
            },
            "from_returns_5": {
                "returns": returns_5.tolist(),
                "correlation_matrix": corr_5.tolist(),
                "enb": enb_5,
                "eigenvalues": eigenvalues_5.tolist(),
            },
        },
        "notes": "ENB = exp(-Σ p_i ln(p_i)) where p_i = λ_i/Σλ. Meucci 2009. "
                 "C# uses Jacobi eigensolver — expect PrecisionStatistical for realistic matrices.",
    })


# ═══════════════════════════════════════════════════════════════════════════
# Generator: DrawdownAnalyzer
# ═══════════════════════════════════════════════════════════════════════════

def gen_drawdown():
    """Phase 4H: DrawdownAnalyzer — period detection."""
    print("Phase 4H: DrawdownAnalyzer")

    # Generate equity curve with known drawdown pattern
    base_date = date(2023, 1, 2)
    daily_returns = RNG.normal(0.0005, 0.015, 252)
    # Inject a clear drawdown: days 50-80 have negative returns
    daily_returns[50:65] = -0.02
    daily_returns[65:80] = 0.015  # Recovery

    equity = [10000.0]
    dates_list = [base_date]
    for i, r in enumerate(daily_returns):
        equity.append(equity[-1] * (1 + r))
        dates_list.append(base_date + timedelta(days=i + 1))

    periods = analyze_drawdown_periods(dates_list, equity)

    # --- Layer 2: Analytical ---
    # At least one drawdown should exist (we injected one)
    hard_check("Drawdown: at least 1 period detected", len(periods) >= 1)

    # Monotonically increasing → no drawdowns
    mono_equity = [10000.0 + i * 10 for i in range(100)]
    mono_dates = [base_date + timedelta(days=i) for i in range(100)]
    mono_periods = analyze_drawdown_periods(mono_dates, mono_equity)
    hard_check("Drawdown: monotonic → 0 periods", len(mono_periods) == 0)

    # Single dip and recovery
    simple_equity = [100.0, 95.0, 90.0, 95.0, 100.0, 105.0]
    simple_dates = [base_date + timedelta(days=i) for i in range(6)]
    simple_periods = analyze_drawdown_periods(simple_dates, simple_equity)
    hard_check("Drawdown: simple dip → 1 period", len(simple_periods) == 1)
    if len(simple_periods) == 1:
        hard_check("Drawdown: simple depth ≈ -10%", abs(simple_periods[0]["depth"] - (-0.10)) < 1e-10)
        # duration = recovery_idx(4) - peak_idx(0) = 4 (peak to recovery, matching C#)
        hard_check("Drawdown: simple duration = 4", simple_periods[0]["duration_days"] == 4)
        hard_check("Drawdown: simple recovery = 2", simple_periods[0]["recovery_days"] == 2)

    # --- Layer 3: Properties ---
    for p in periods:
        hard_check(f"Drawdown: depth ∈ [-1,0] ({p['depth']:.4f})", -1.0 <= p["depth"] <= 0.0)
        hard_check(f"Drawdown: duration > 0", p["duration_days"] > 0)
        if p["recovery_days"] is not None:
            hard_check(f"Drawdown: recovery ≥ 0", p["recovery_days"] >= 0)

    # Ongoing drawdown (no recovery at end)
    declining_equity = [100.0, 95.0, 90.0, 85.0, 80.0]
    declining_dates = [base_date + timedelta(days=i) for i in range(5)]
    declining_periods = analyze_drawdown_periods(declining_dates, declining_equity)
    hard_check("Drawdown: declining → 1 ongoing period", len(declining_periods) == 1)
    if len(declining_periods) == 1:
        hard_check("Drawdown: ongoing has no recovery date",
                   declining_periods[0]["recovery_date"] is None)
        hard_check("Drawdown: ongoing has no recovery days",
                   declining_periods[0]["recovery_days"] is None)
        hard_check("Drawdown: ongoing depth = -20%",
                   abs(declining_periods[0]["depth"] - (-0.20)) < 1e-10)

    save("analytics_drawdown", {
        "cases": {
            "full_year": {
                "dates": [d.isoformat() for d in dates_list],
                "equity": equity,
                "periods": periods,
            },
            "monotonic": {
                "dates": [d.isoformat() for d in mono_dates],
                "equity": mono_equity,
                "periods": mono_periods,
            },
            "simple_dip": {
                "dates": [d.isoformat() for d in simple_dates],
                "equity": simple_equity,
                "periods": simple_periods,
            },
            "ongoing_decline": {
                "dates": [d.isoformat() for d in declining_dates],
                "equity": declining_equity,
                "periods": declining_periods,
            },
        },
        "notes": "DrawdownAnalyzer: tracks peak→trough→recovery. Duration in trading days (index-based).",
    })


# ═══════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════

def main():
    print("=" * 70)
    print("Phase 4 Analytics: Generating verification vectors")
    print("=" * 70)

    gen_brinson_fachler()
    gen_factor_regression()
    gen_correlation()
    gen_enb()
    gen_drawdown()

    # Summary
    print()
    print("=" * 70)
    hard_passed = sum(1 for _, ok in HARD_CHECKS if ok)
    hard_total = len(HARD_CHECKS)
    print(f"HARD checks:    {hard_passed}/{hard_total} passed")
    if hard_passed < hard_total:
        for name, ok in HARD_CHECKS:
            if not ok:
                print(f"  ✗ {name}")

    qual_passed = sum(1 for _, ok, _ in QUALITY_CHECKS if ok)
    qual_total = len(QUALITY_CHECKS)
    print(f"QUALITY checks: {qual_passed}/{qual_total} passed")
    for name, ok, detail in QUALITY_CHECKS:
        status = "✓" if ok else "✗"
        print(f"  {status} {name} ({detail})")

    print("=" * 70)


if __name__ == "__main__":
    main()
