<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Boutquin.MarketData.DependencyInjection" />
    <PackageReference Include="Boutquin.MarketData.Adapter.Tiingo" />
    <PackageReference Include="Boutquin.MarketData.Adapter.Frankfurter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Boutquin.Trading.Application.csproj" />
    <ProjectReference Include="..\Recipes\Boutquin.Trading.Recipes.csproj" />
  </ItemGroup>

</Project>
