// <auto-generated />
using System;
using Boutquin.Trading.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Boutquin.Trading.DataAccess.Migrations
{
    [DbContext(typeof(SecurityMasterContext))]
    partial class SecurityMasterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.AssetClass", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("AssetClasses");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Cash or Cash Equivalents"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Fixed Income Securities"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Equity Securities"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Real Estate"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Commodities"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Alternative Investments"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Crypto-Currencies"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.City", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TimeZoneCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("_id");

                    b.HasIndex("TimeZoneCode");

                    b.HasIndex("CountryCode", "Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            _id = 1,
                            CountryCode = "US",
                            Name = "New York",
                            TimeZoneCode = "UTC"
                        },
                        new
                        {
                            _id = 2,
                            CountryCode = "JP",
                            Name = "Tokyo",
                            TimeZoneCode = "JST"
                        },
                        new
                        {
                            _id = 3,
                            CountryCode = "CN",
                            Name = "Shanghai",
                            TimeZoneCode = "CST"
                        },
                        new
                        {
                            _id = 4,
                            CountryCode = "HK",
                            Name = "Hong Kong",
                            TimeZoneCode = "HKT"
                        },
                        new
                        {
                            _id = 5,
                            CountryCode = "FR",
                            Name = "Paris",
                            TimeZoneCode = "CET"
                        },
                        new
                        {
                            _id = 6,
                            CountryCode = "GB",
                            Name = "London",
                            TimeZoneCode = "GMT"
                        },
                        new
                        {
                            _id = 7,
                            CountryCode = "DE",
                            Name = "Frankfurt",
                            TimeZoneCode = "CET"
                        },
                        new
                        {
                            _id = 8,
                            CountryCode = "RU",
                            Name = "Moscow",
                            TimeZoneCode = "MSK"
                        },
                        new
                        {
                            _id = 9,
                            CountryCode = "CA",
                            Name = "Toronto",
                            TimeZoneCode = "EST"
                        });
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.Continent", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Code");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Continents");

                    b.HasData(
                        new
                        {
                            Code = "AF",
                            Name = "Africa"
                        },
                        new
                        {
                            Code = "AN",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Code = "AS",
                            Name = "Asia"
                        },
                        new
                        {
                            Code = "EU",
                            Name = "Europe"
                        },
                        new
                        {
                            Code = "NA",
                            Name = "North America"
                        },
                        new
                        {
                            Code = "OC",
                            Name = "Oceania"
                        },
                        new
                        {
                            Code = "SA",
                            Name = "South America"
                        });
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ContinentCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumericCode")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.HasIndex("ContinentCode");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "CA",
                            ContinentCode = "NA",
                            CurrencyCode = "CAD",
                            Name = "Canada",
                            NumericCode = 124
                        },
                        new
                        {
                            Code = "CN",
                            ContinentCode = "AS",
                            CurrencyCode = "CNY",
                            Name = "China",
                            NumericCode = 156
                        },
                        new
                        {
                            Code = "FR",
                            ContinentCode = "EU",
                            CurrencyCode = "EUR",
                            Name = "France",
                            NumericCode = 250
                        },
                        new
                        {
                            Code = "DE",
                            ContinentCode = "EU",
                            CurrencyCode = "EUR",
                            Name = "Germany",
                            NumericCode = 276
                        },
                        new
                        {
                            Code = "HK",
                            ContinentCode = "AS",
                            CurrencyCode = "HKD",
                            Name = "Hong Kong",
                            NumericCode = 344
                        },
                        new
                        {
                            Code = "IN",
                            ContinentCode = "AS",
                            CurrencyCode = "INR",
                            Name = "India",
                            NumericCode = 356
                        },
                        new
                        {
                            Code = "JP",
                            ContinentCode = "AS",
                            CurrencyCode = "JPY",
                            Name = "Japan",
                            NumericCode = 392
                        },
                        new
                        {
                            Code = "RU",
                            ContinentCode = "EU",
                            CurrencyCode = "RUB",
                            Name = "Russia",
                            NumericCode = 643
                        },
                        new
                        {
                            Code = "KR",
                            ContinentCode = "AS",
                            CurrencyCode = "KRW",
                            Name = "South Korea",
                            NumericCode = 410
                        },
                        new
                        {
                            Code = "GB",
                            ContinentCode = "EU",
                            CurrencyCode = "GBP",
                            Name = "United Kingdom",
                            NumericCode = 826
                        },
                        new
                        {
                            Code = "US",
                            ContinentCode = "NA",
                            CurrencyCode = "USD",
                            Name = "United States",
                            NumericCode = 840
                        });
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumericCode")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Code");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NumericCode")
                        .IsUnique();

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Code = "USD",
                            Name = "United States dollar",
                            NumericCode = 840,
                            Symbol = "$"
                        },
                        new
                        {
                            Code = "CAD",
                            Name = "Canadian dollar",
                            NumericCode = 124,
                            Symbol = "$"
                        },
                        new
                        {
                            Code = "MXN",
                            Name = "Mexican peso",
                            NumericCode = 484,
                            Symbol = "$"
                        },
                        new
                        {
                            Code = "GBP",
                            Name = "British pound",
                            NumericCode = 826,
                            Symbol = "£"
                        },
                        new
                        {
                            Code = "EUR",
                            Name = "Euro",
                            NumericCode = 978,
                            Symbol = "€"
                        },
                        new
                        {
                            Code = "JPY",
                            Name = "Japanese yen",
                            NumericCode = 392,
                            Symbol = "¥"
                        },
                        new
                        {
                            Code = "CNY",
                            Name = "Chinese yuan",
                            NumericCode = 156,
                            Symbol = "¥"
                        },
                        new
                        {
                            Code = "INR",
                            Name = "Indian rupee",
                            NumericCode = 356,
                            Symbol = "₹"
                        },
                        new
                        {
                            Code = "AUD",
                            Name = "Australian dollar",
                            NumericCode = 36,
                            Symbol = "$"
                        },
                        new
                        {
                            Code = "BRL",
                            Name = "Brazilian real",
                            NumericCode = 986,
                            Symbol = "R$"
                        },
                        new
                        {
                            Code = "RUB",
                            Name = "Russian ruble",
                            NumericCode = 643,
                            Symbol = "₽"
                        },
                        new
                        {
                            Code = "KRW",
                            Name = "South Korean won",
                            NumericCode = 410,
                            Symbol = "₩"
                        },
                        new
                        {
                            Code = "HKD",
                            Name = "Hong Kong dollar",
                            NumericCode = 344,
                            Symbol = "HK$"
                        });
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.Exchange", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Code");

                    b.HasIndex("CityId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Exchanges");

                    b.HasData(
                        new
                        {
                            Code = "XNYS",
                            CityId = 1,
                            Name = "New York Stock Exchange"
                        },
                        new
                        {
                            Code = "XNAS",
                            CityId = 1,
                            Name = "NASDAQ Stock Market"
                        },
                        new
                        {
                            Code = "XTSE",
                            CityId = 2,
                            Name = "Tokyo Stock Exchange"
                        },
                        new
                        {
                            Code = "XSHG",
                            CityId = 3,
                            Name = "Shanghai Stock Exchange"
                        },
                        new
                        {
                            Code = "XHKG",
                            CityId = 4,
                            Name = "Hong Kong Stock Exchange"
                        },
                        new
                        {
                            Code = "XPAR",
                            CityId = 5,
                            Name = "Euronext Paris"
                        },
                        new
                        {
                            Code = "XLON",
                            CityId = 6,
                            Name = "London Stock Exchange"
                        },
                        new
                        {
                            Code = "XETR",
                            CityId = 7,
                            Name = "Deutsche Boerse XETRA"
                        },
                        new
                        {
                            Code = "XMOS",
                            CityId = 8,
                            Name = "Moscow Exchange"
                        },
                        new
                        {
                            Code = "XTOR",
                            CityId = 9,
                            Name = "Toronto Stock Exchange"
                        });
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.ExchangeHoliday", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExchangeCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("Date");

                    b.HasKey("_id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.HasIndex("ExchangeCode", "HolidayDate")
                        .IsUnique();

                    b.ToTable("ExchangeHolidays");
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.ExchangeSchedule", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"));

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("ExchangeCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.HasKey("_id");

                    b.HasIndex("ExchangeCode", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("ExchangeSchedules");

                    b.HasData(
                        new
                        {
                            _id = 1,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 1,
                            ExchangeCode = "XNYS",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 2,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 2,
                            ExchangeCode = "XNYS",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 3,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 3,
                            ExchangeCode = "XNYS",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 4,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 4,
                            ExchangeCode = "XNYS",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 5,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 5,
                            ExchangeCode = "XNYS",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 6,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 1,
                            ExchangeCode = "XNAS",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 7,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 2,
                            ExchangeCode = "XNAS",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 8,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 3,
                            ExchangeCode = "XNAS",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 9,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 4,
                            ExchangeCode = "XNAS",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 10,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 5,
                            ExchangeCode = "XNAS",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 11,
                            CloseTime = new TimeSpan(0, 15, 0, 0, 0),
                            DayOfWeek = 1,
                            ExchangeCode = "XTSE",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 12,
                            CloseTime = new TimeSpan(0, 15, 0, 0, 0),
                            DayOfWeek = 2,
                            ExchangeCode = "XTSE",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 13,
                            CloseTime = new TimeSpan(0, 15, 0, 0, 0),
                            DayOfWeek = 3,
                            ExchangeCode = "XTSE",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 14,
                            CloseTime = new TimeSpan(0, 15, 0, 0, 0),
                            DayOfWeek = 4,
                            ExchangeCode = "XTSE",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 15,
                            CloseTime = new TimeSpan(0, 15, 0, 0, 0),
                            DayOfWeek = 5,
                            ExchangeCode = "XTSE",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 16,
                            CloseTime = new TimeSpan(0, 15, 0, 0, 0),
                            DayOfWeek = 1,
                            ExchangeCode = "XSHG",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 17,
                            CloseTime = new TimeSpan(0, 15, 0, 0, 0),
                            DayOfWeek = 2,
                            ExchangeCode = "XSHG",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 18,
                            CloseTime = new TimeSpan(0, 15, 0, 0, 0),
                            DayOfWeek = 3,
                            ExchangeCode = "XSHG",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 19,
                            CloseTime = new TimeSpan(0, 15, 0, 0, 0),
                            DayOfWeek = 4,
                            ExchangeCode = "XSHG",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 20,
                            CloseTime = new TimeSpan(0, 15, 0, 0, 0),
                            DayOfWeek = 5,
                            ExchangeCode = "XSHG",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 21,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 1,
                            ExchangeCode = "XHKG",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 22,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 2,
                            ExchangeCode = "XHKG",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 23,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 3,
                            ExchangeCode = "XHKG",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 24,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 4,
                            ExchangeCode = "XHKG",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 25,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 5,
                            ExchangeCode = "XHKG",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 26,
                            CloseTime = new TimeSpan(0, 17, 30, 0, 0),
                            DayOfWeek = 1,
                            ExchangeCode = "XPAR",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 27,
                            CloseTime = new TimeSpan(0, 17, 30, 0, 0),
                            DayOfWeek = 2,
                            ExchangeCode = "XPAR",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 28,
                            CloseTime = new TimeSpan(0, 17, 30, 0, 0),
                            DayOfWeek = 3,
                            ExchangeCode = "XPAR",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 29,
                            CloseTime = new TimeSpan(0, 17, 30, 0, 0),
                            DayOfWeek = 4,
                            ExchangeCode = "XPAR",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 30,
                            CloseTime = new TimeSpan(0, 17, 30, 0, 0),
                            DayOfWeek = 5,
                            ExchangeCode = "XPAR",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 31,
                            CloseTime = new TimeSpan(0, 16, 30, 0, 0),
                            DayOfWeek = 1,
                            ExchangeCode = "XLON",
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            _id = 32,
                            CloseTime = new TimeSpan(0, 16, 30, 0, 0),
                            DayOfWeek = 2,
                            ExchangeCode = "XLON",
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            _id = 33,
                            CloseTime = new TimeSpan(0, 16, 30, 0, 0),
                            DayOfWeek = 3,
                            ExchangeCode = "XLON",
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            _id = 34,
                            CloseTime = new TimeSpan(0, 16, 30, 0, 0),
                            DayOfWeek = 4,
                            ExchangeCode = "XLON",
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            _id = 35,
                            CloseTime = new TimeSpan(0, 16, 30, 0, 0),
                            DayOfWeek = 5,
                            ExchangeCode = "XLON",
                            OpenTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            _id = 36,
                            CloseTime = new TimeSpan(0, 17, 30, 0, 0),
                            DayOfWeek = 1,
                            ExchangeCode = "XETR",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 37,
                            CloseTime = new TimeSpan(0, 17, 30, 0, 0),
                            DayOfWeek = 2,
                            ExchangeCode = "XETR",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 38,
                            CloseTime = new TimeSpan(0, 17, 30, 0, 0),
                            DayOfWeek = 3,
                            ExchangeCode = "XETR",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 39,
                            CloseTime = new TimeSpan(0, 17, 30, 0, 0),
                            DayOfWeek = 4,
                            ExchangeCode = "XETR",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 40,
                            CloseTime = new TimeSpan(0, 17, 30, 0, 0),
                            DayOfWeek = 5,
                            ExchangeCode = "XETR",
                            OpenTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            _id = 41,
                            CloseTime = new TimeSpan(0, 18, 45, 0, 0),
                            DayOfWeek = 1,
                            ExchangeCode = "XMOS",
                            OpenTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            _id = 42,
                            CloseTime = new TimeSpan(0, 18, 45, 0, 0),
                            DayOfWeek = 2,
                            ExchangeCode = "XMOS",
                            OpenTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            _id = 43,
                            CloseTime = new TimeSpan(0, 18, 45, 0, 0),
                            DayOfWeek = 3,
                            ExchangeCode = "XMOS",
                            OpenTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            _id = 44,
                            CloseTime = new TimeSpan(0, 18, 45, 0, 0),
                            DayOfWeek = 4,
                            ExchangeCode = "XMOS",
                            OpenTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            _id = 45,
                            CloseTime = new TimeSpan(0, 18, 45, 0, 0),
                            DayOfWeek = 5,
                            ExchangeCode = "XMOS",
                            OpenTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            _id = 46,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 1,
                            ExchangeCode = "XTOR",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 47,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 2,
                            ExchangeCode = "XTOR",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 48,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 3,
                            ExchangeCode = "XTOR",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 49,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 4,
                            ExchangeCode = "XTOR",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        },
                        new
                        {
                            _id = 50,
                            CloseTime = new TimeSpan(0, 16, 0, 0, 0),
                            DayOfWeek = 5,
                            ExchangeCode = "XTOR",
                            OpenTime = new TimeSpan(0, 9, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.FxRate", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"));

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("QuoteCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RateDate")
                        .HasColumnType("Date");

                    b.HasKey("_id");

                    b.HasIndex("BaseCurrencyCode");

                    b.HasIndex("QuoteCurrencyCode");

                    b.HasIndex("RateDate", "BaseCurrencyCode", "QuoteCurrencyCode")
                        .IsUnique();

                    b.ToTable("FxRates");
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.Security", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"));

                    b.Property<int>("AssetClassCode")
                        .HasColumnType("int");

                    b.Property<string>("ExchangeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("_id");

                    b.HasIndex("AssetClassCode");

                    b.HasIndex("ExchangeCode");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Securities");
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.SecurityPrice", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"));

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Dividend")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpenPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SecurityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("Date");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("_id");

                    b.HasIndex("SecurityId");

                    b.HasIndex("TradeDate", "SecurityId")
                        .IsUnique();

                    b.ToTable("SecurityPrices");
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.SecuritySymbol", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("_id"));

                    b.Property<int>("SecurityId")
                        .HasColumnType("int");

                    b.Property<int>("Standard")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("_id");

                    b.HasIndex("Standard");

                    b.HasIndex("SecurityId", "Standard")
                        .IsUnique();

                    b.ToTable("SecuritySymbols");
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.SymbolStandard", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("SymbolStandards");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "CUSIP"
                        },
                        new
                        {
                            Id = 1,
                            Description = "ISIN"
                        },
                        new
                        {
                            Id = 2,
                            Description = "SEDOL"
                        },
                        new
                        {
                            Id = 3,
                            Description = "RIC"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bloomberg Ticker"
                        });
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.TimeZone", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TimeZoneOffset")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool>("UsesDaylightSaving")
                        .HasColumnType("bit");

                    b.HasKey("Code");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TimeZones");

                    b.HasData(
                        new
                        {
                            Code = "UTC",
                            Name = "Coordinated Universal Time",
                            TimeZoneOffset = "Z",
                            UsesDaylightSaving = false
                        },
                        new
                        {
                            Code = "CET",
                            Name = "Central European Time",
                            TimeZoneOffset = "+01:00",
                            UsesDaylightSaving = false
                        },
                        new
                        {
                            Code = "GMT",
                            Name = "Greenwich Mean Time",
                            TimeZoneOffset = "GMT",
                            UsesDaylightSaving = false
                        },
                        new
                        {
                            Code = "EST",
                            Name = "Eastern Standard Time",
                            TimeZoneOffset = "-05:00",
                            UsesDaylightSaving = false
                        },
                        new
                        {
                            Code = "CST",
                            Name = "China Standard Time",
                            TimeZoneOffset = "+08:00",
                            UsesDaylightSaving = false
                        },
                        new
                        {
                            Code = "JST",
                            Name = "Japan Standard Time",
                            TimeZoneOffset = "+09:00",
                            UsesDaylightSaving = false
                        },
                        new
                        {
                            Code = "HKT",
                            Name = "Hong Kong Time",
                            TimeZoneOffset = "+08:00",
                            UsesDaylightSaving = false
                        },
                        new
                        {
                            Code = "MSK",
                            Name = "Moscow Standard Time",
                            TimeZoneOffset = "+04:00",
                            UsesDaylightSaving = false
                        },
                        new
                        {
                            Code = "AEST",
                            Name = "Australian Eastern Standard Time",
                            TimeZoneOffset = "+10:00",
                            UsesDaylightSaving = false
                        });
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.City", b =>
                {
                    b.HasOne("Boutquin.Trading.Domain.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boutquin.Trading.Domain.Entities.TimeZone", null)
                        .WithMany()
                        .HasForeignKey("TimeZoneCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.Country", b =>
                {
                    b.HasOne("Boutquin.Trading.Domain.Entities.Continent", null)
                        .WithMany()
                        .HasForeignKey("ContinentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boutquin.Trading.Domain.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.Exchange", b =>
                {
                    b.HasOne("Boutquin.Trading.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.ExchangeHoliday", b =>
                {
                    b.HasOne("Boutquin.Trading.Domain.Entities.Exchange", null)
                        .WithMany("ExchangeHolidays")
                        .HasForeignKey("ExchangeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.ExchangeSchedule", b =>
                {
                    b.HasOne("Boutquin.Trading.Domain.Entities.Exchange", null)
                        .WithMany("ExchangeSchedules")
                        .HasForeignKey("ExchangeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.FxRate", b =>
                {
                    b.HasOne("Boutquin.Trading.Domain.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("BaseCurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boutquin.Trading.Domain.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("QuoteCurrencyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.Security", b =>
                {
                    b.HasOne("Boutquin.Trading.Domain.Entities.AssetClass", null)
                        .WithMany()
                        .HasForeignKey("AssetClassCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boutquin.Trading.Domain.Entities.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.SecurityPrice", b =>
                {
                    b.HasOne("Boutquin.Trading.Domain.Entities.Security", null)
                        .WithMany("SecurityPrices")
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.SecuritySymbol", b =>
                {
                    b.HasOne("Boutquin.Trading.Domain.Entities.Security", null)
                        .WithMany("SecuritySymbols")
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boutquin.Trading.Domain.Entities.SymbolStandard", null)
                        .WithMany()
                        .HasForeignKey("Standard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.Exchange", b =>
                {
                    b.Navigation("ExchangeHolidays");

                    b.Navigation("ExchangeSchedules");
                });

            modelBuilder.Entity("Boutquin.Trading.Domain.Entities.Security", b =>
                {
                    b.Navigation("SecurityPrices");

                    b.Navigation("SecuritySymbols");
                });
#pragma warning restore 612, 618
        }
    }
}
