// Copyright (c) 2023-2024 Pierre G. Boutquin. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License").
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
namespace Boutquin.Trading.Domain.Enums;

/// /// <summary>
/// The SignalType enum represents different types of trading signals or
/// recommendations generated by a trading strategy.
/// </summary>
public enum SignalType
{
    /// <summary>
    /// No signal or recommendation.
    /// </summary>
    None = 0,

    /// <summary>
    /// A recommendation to increase the holding of an asset,
    /// based on the investment or trading system analysis.
    /// </summary>
    Overweight,

    /// <summary>
    /// A recommendation to hold an asset without making any changes,
    /// based on the investment or trading system analysis.
    /// </summary>
    Hold,

    /// <summary>
    /// A recommendation to decrease the holding of an asset,
    /// based on the investment or trading system analysis.
    /// </summary>
    Underweight,

    /// <summary>
    /// A recommendation to rebalance the portfolio,
    /// based on the investment or trading system analysis.
    /// </summary>
    Rebalance,

    /// <summary>
    /// A recommendation to completely sell off or exit a position in an asset,
    /// based on the investment or trading system analysis.
    /// </summary>
    Exit
}
